import type { Lead, DealGrade, VerdictTier } from "./types"

function generateCashFlowTrend(base: number, volatility: number = 0.1): number[] {
  const trend: number[] = []
  let current = base
  for (let i = 0; i < 12; i++) {
    current = current * (1 + (Math.random() - 0.5) * volatility)
    trend.push(Math.round(current))
  }
  return trend
}

function getGradeFromScore(score: number): DealGrade {
  if (score >= 85) return "A"
  if (score >= 70) return "B"
  if (score >= 55) return "C"
  if (score >= 40) return "D"
  return "F"
}

function getTierFromScore(score: number): VerdictTier {
  if (score >= 85) return "STRONG BUY"
  if (score >= 70) return "GOOD DEAL"
  if (score >= 55) return "BORDERLINE"
  if (score >= 40) return "PASS"
  return "AVOID"
}

export const mockLeads: Lead[] = [
  {
    id: "lead-001",
    propertyFacts: {
      beds: 3,
      baths: 2,
      sqft: 1850,
      yearBuilt: 1998,
      propertyType: "Single Family",
      lastSalePrice: 285000,
      lastSaleDate: "2019-06-15",
      address: "4521 Magnolia Drive",
      city: "Austin",
      state: "TX",
      zip: "78745",
      imageUrl: "/placeholder.svg?height=200&width=300",
    },
    inputs: {
      purchase: {
        purchasePrice: 385000,
        downPaymentPercent: 25,
        closingCostsPercent: 3,
        rehabCosts: 15000,
      },
      financing: {
        loanInterestRate: 6.875,
        loanTermYears: 30,
      },
      income: {
        monthlyRent: 2850,
        otherMonthlyIncome: 0,
        vacancyRatePercent: 5,
      },
      operatingExpenses: {
        annualPropertyTax: 7700,
        annualInsurance: 2100,
        monthlyHOA: 0,
        monthlyUtilities: 0,
        maintenancePercent: 5,
        propertyManagementPercent: 8,
        capexReservePercent: 5,
      },
      growthAndExit: {
        annualAppreciationPercent: 4.2,
        annualRentGrowthPercent: 3,
        annualExpenseGrowthPercent: 2.5,
        sellingCostsPercent: 6,
        holdPeriodYears: 10,
      },
    },
    outputs: {
      upfront: {
        loanAmount: 288750,
        downPayment: 96250,
        closingCosts: 11550,
        totalCashInvested: 122800,
      },
      monthly: {
        monthlyMortgagePayment: 1897,
        monthlyGrossRent: 2850,
        monthlyEffectiveIncome: 2708,
        monthlyOperatingExpenses: 1330,
        monthlyCashFlow: 481,
        monthlyNOI: 1378,
      },
      annual: {
        annualGrossIncome: 34200,
        annualEffectiveIncome: 32490,
        annualOperatingExpenses: 15960,
        annualNOI: 16530,
        annualDebtService: 22764,
        annualCashFlow: 5766,
      },
      ratios: {
        capRate: 4.13,
        cashOnCashReturn: 4.69,
        dscr: 1.43,
        irr: 14.2,
        grossRentMultiplier: 11.26,
        onePercentRule: 0.74,
        operatingExpenseRatio: 0.49,
        breakEvenOccupancy: 0.83,
      },
      exit: {
        salePrice: 578500,
        sellingCosts: 34710,
        loanBalanceAtExit: 232890,
        netSaleProceeds: 310900,
        totalCashFlow: 68420,
        totalPrincipalPaydown: 55860,
        totalAppreciation: 193500,
        totalProfit: 256520,
        totalROI: 208.9,
        averageAnnualReturn: 20.89,
      },
      projections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        grossRent: Math.round(34200 * Math.pow(1.03, i)),
        effectiveGrossIncome: Math.round(32490 * Math.pow(1.03, i)),
        operatingExpenses: Math.round(15960 * Math.pow(1.025, i)),
        noi: Math.round(16530 * Math.pow(1.025, i)),
        debtService: 22764,
        cashFlow: Math.round(5766 + i * 450),
        principalPaid: Math.round(4200 + i * 280),
        interestPaid: Math.round(18564 - i * 280),
        loanBalanceEnd: Math.round(288750 - (4200 + i * 280) * (i + 1)),
        propertyValueEnd: Math.round(385000 * Math.pow(1.042, i + 1)),
        equityEnd: Math.round(96250 + (4200 + i * 280) * (i + 1) + 385000 * (Math.pow(1.042, i + 1) - 1)),
        cumulativeCashFlow: Math.round((5766 + i * 225) * (i + 1)),
      })),
    },
    verdict: {
      tier: "GOOD DEAL",
      score: 72,
      rubric: [
        { name: "Cash-on-cash", score: 6, maxPoints: 12, status: "ok" },
        { name: "Cap rate", score: 8, maxPoints: 15, status: "warn" },
        { name: "DSCR", score: 12, maxPoints: 15, status: "ok" },
        { name: "IRR", score: 18, maxPoints: 22, status: "win" },
        { name: "Vacancy tolerance", score: 7, maxPoints: 10, status: "ok" },
        { name: "Price-to-rent", score: 4, maxPoints: 7, status: "ok" },
        { name: "Total ROI", score: 10, maxPoints: 10, status: "win" },
      ],
      summary: "Solid cash flow with strong appreciation potential. DSCR provides comfortable margin above 1.25x. IRR projections indicate excellent long-term returns.",
    },
    grade: "B",
    provenance: {
      purchasePrice: { source: "zillow-listing", confidence: "high", tooltip: "List price from Zillow" },
      monthlyRent: { source: "rent-comps", confidence: "medium", tooltip: "RentCast comparable analysis" },
      loanInterestRate: { source: "fred", confidence: "high", tooltip: "30yr fixed from Freddie Mac PMMS" },
      annualPropertyTax: { source: "rentcast", confidence: "high", tooltip: "County tax records" },
      annualInsurance: { source: "state-average", confidence: "medium", tooltip: "TX state average" },
      annualAppreciationPercent: { source: "fhfa-hpi", confidence: "high", tooltip: "Austin MSA 5yr CAGR" },
    },
    createdAt: new Date("2024-01-15T10:30:00"),
    cashFlowTrend: generateCashFlowTrend(481, 0.08),
  },
  {
    id: "lead-002",
    propertyFacts: {
      beds: 4,
      baths: 2.5,
      sqft: 2200,
      yearBuilt: 2015,
      propertyType: "Single Family",
      lastSalePrice: 420000,
      lastSaleDate: "2021-03-22",
      address: "892 Oakwood Lane",
      city: "Tampa",
      state: "FL",
      zip: "33624",
      floodZone: { zone: "AE", risk: "high", label: "100-Year Flood Zone", isCoastalHigh: false },
    },
    inputs: {
      purchase: {
        purchasePrice: 525000,
        downPaymentPercent: 20,
        closingCostsPercent: 3,
        rehabCosts: 0,
      },
      financing: {
        loanInterestRate: 6.875,
        loanTermYears: 30,
      },
      income: {
        monthlyRent: 3200,
        otherMonthlyIncome: 100,
        vacancyRatePercent: 5,
      },
      operatingExpenses: {
        annualPropertyTax: 9450,
        annualInsurance: 4800,
        monthlyHOA: 125,
        monthlyUtilities: 0,
        maintenancePercent: 5,
        propertyManagementPercent: 10,
        capexReservePercent: 5,
      },
      growthAndExit: {
        annualAppreciationPercent: 3.8,
        annualRentGrowthPercent: 3,
        annualExpenseGrowthPercent: 2.5,
        sellingCostsPercent: 6,
        holdPeriodYears: 10,
      },
    },
    outputs: {
      upfront: {
        loanAmount: 420000,
        downPayment: 105000,
        closingCosts: 15750,
        totalCashInvested: 120750,
      },
      monthly: {
        monthlyMortgagePayment: 2759,
        monthlyGrossRent: 3300,
        monthlyEffectiveIncome: 3135,
        monthlyOperatingExpenses: 1854,
        monthlyCashFlow: -478,
        monthlyNOI: 1281,
      },
      annual: {
        annualGrossIncome: 39600,
        annualEffectiveIncome: 37620,
        annualOperatingExpenses: 22248,
        annualNOI: 15372,
        annualDebtService: 33108,
        annualCashFlow: -5736,
      },
      ratios: {
        capRate: 2.93,
        cashOnCashReturn: -4.75,
        dscr: 0.93,
        irr: 8.1,
        grossRentMultiplier: 13.26,
        onePercentRule: 0.63,
        operatingExpenseRatio: 0.59,
        breakEvenOccupancy: 0.98,
      },
      exit: {
        salePrice: 752000,
        sellingCosts: 45120,
        loanBalanceAtExit: 338500,
        netSaleProceeds: 368380,
        totalCashFlow: -57360,
        totalPrincipalPaydown: 81500,
        totalAppreciation: 227000,
        totalProfit: 190270,
        totalROI: 157.6,
        averageAnnualReturn: 15.76,
      },
      projections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        grossRent: Math.round(39600 * Math.pow(1.03, i)),
        effectiveGrossIncome: Math.round(37620 * Math.pow(1.03, i)),
        operatingExpenses: Math.round(22248 * Math.pow(1.025, i)),
        noi: Math.round(15372 * Math.pow(1.02, i)),
        debtService: 33108,
        cashFlow: Math.round(-5736 + i * 620),
        principalPaid: Math.round(6100 + i * 400),
        interestPaid: Math.round(27008 - i * 400),
        loanBalanceEnd: Math.round(420000 - (6100 + i * 400) * (i + 1)),
        propertyValueEnd: Math.round(525000 * Math.pow(1.038, i + 1)),
        equityEnd: Math.round(105000 + (6100 + i * 400) * (i + 1) + 525000 * (Math.pow(1.038, i + 1) - 1)),
        cumulativeCashFlow: Math.round((-5736 + i * 310) * (i + 1)),
      })),
    },
    verdict: {
      tier: "PASS",
      score: 42,
      rubric: [
        { name: "Cash-on-cash", score: 0, maxPoints: 12, status: "fail" },
        { name: "Cap rate", score: 4, maxPoints: 15, status: "fail" },
        { name: "DSCR", score: 3, maxPoints: 15, status: "fail" },
        { name: "IRR", score: 12, maxPoints: 22, status: "ok" },
        { name: "Vacancy tolerance", score: 2, maxPoints: 10, status: "fail" },
        { name: "Price-to-rent", score: 3, maxPoints: 7, status: "warn" },
        { name: "Total ROI", score: 8, maxPoints: 10, status: "ok" },
      ],
      summary: "Negative cash flow property banking on appreciation. High insurance costs due to flood zone. DSCR below 1.0 indicates income does not cover debt service.",
    },
    grade: "D",
    provenance: {
      purchasePrice: { source: "zillow-listing", confidence: "high" },
      monthlyRent: { source: "zillow-listing", confidence: "low", tooltip: "Zillow rentZestimate" },
      annualInsurance: { source: "fema-nfhl", confidence: "medium", tooltip: "Flood zone AE bump applied" },
      annualPropertyTax: { source: "state-investor-rate", confidence: "medium", tooltip: "FL non-homestead rate" },
    },
    createdAt: new Date("2024-01-14T14:22:00"),
    cashFlowTrend: generateCashFlowTrend(-478, 0.15),
  },
  {
    id: "lead-003",
    propertyFacts: {
      beds: 2,
      baths: 1,
      sqft: 1100,
      yearBuilt: 1965,
      propertyType: "Single Family",
      lastSalePrice: 89000,
      lastSaleDate: "2018-09-10",
      address: "1847 Elm Street",
      city: "Indianapolis",
      state: "IN",
      zip: "46201",
    },
    inputs: {
      purchase: {
        purchasePrice: 145000,
        downPaymentPercent: 25,
        closingCostsPercent: 3,
        rehabCosts: 25000,
      },
      financing: {
        loanInterestRate: 6.875,
        loanTermYears: 30,
      },
      income: {
        monthlyRent: 1450,
        otherMonthlyIncome: 0,
        vacancyRatePercent: 8,
      },
      operatingExpenses: {
        annualPropertyTax: 1740,
        annualInsurance: 1200,
        monthlyHOA: 0,
        monthlyUtilities: 0,
        maintenancePercent: 8,
        propertyManagementPercent: 10,
        capexReservePercent: 8,
      },
      growthAndExit: {
        annualAppreciationPercent: 3.2,
        annualRentGrowthPercent: 2.5,
        annualExpenseGrowthPercent: 2.5,
        sellingCostsPercent: 6,
        holdPeriodYears: 10,
      },
    },
    outputs: {
      upfront: {
        loanAmount: 108750,
        downPayment: 36250,
        closingCosts: 4350,
        totalCashInvested: 65600,
      },
      monthly: {
        monthlyMortgagePayment: 714,
        monthlyGrossRent: 1450,
        monthlyEffectiveIncome: 1334,
        monthlyOperatingExpenses: 623,
        monthlyCashFlow: 497,
        monthlyNOI: 711,
      },
      annual: {
        annualGrossIncome: 17400,
        annualEffectiveIncome: 16008,
        annualOperatingExpenses: 7476,
        annualNOI: 8532,
        annualDebtService: 8568,
        annualCashFlow: 5964,
      },
      ratios: {
        capRate: 5.02,
        cashOnCashReturn: 9.09,
        dscr: 1.57,
        irr: 16.8,
        grossRentMultiplier: 9.77,
        onePercentRule: 0.85,
        operatingExpenseRatio: 0.47,
        breakEvenOccupancy: 0.72,
      },
      exit: {
        salePrice: 199500,
        sellingCosts: 11970,
        loanBalanceAtExit: 87720,
        netSaleProceeds: 99810,
        totalCashFlow: 71200,
        totalPrincipalPaydown: 21030,
        totalAppreciation: 54500,
        totalProfit: 105410,
        totalROI: 160.7,
        averageAnnualReturn: 16.07,
      },
      projections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        grossRent: Math.round(17400 * Math.pow(1.025, i)),
        effectiveGrossIncome: Math.round(16008 * Math.pow(1.025, i)),
        operatingExpenses: Math.round(7476 * Math.pow(1.025, i)),
        noi: Math.round(8532 * Math.pow(1.025, i)),
        debtService: 8568,
        cashFlow: Math.round(5964 + i * 180),
        principalPaid: Math.round(1580 + i * 105),
        interestPaid: Math.round(6988 - i * 105),
        loanBalanceEnd: Math.round(108750 - (1580 + i * 105) * (i + 1)),
        propertyValueEnd: Math.round(170000 * Math.pow(1.032, i + 1)),
        equityEnd: Math.round(61250 + (1580 + i * 105) * (i + 1) + 170000 * (Math.pow(1.032, i + 1) - 1)),
        cumulativeCashFlow: Math.round((5964 + i * 90) * (i + 1)),
      })),
    },
    verdict: {
      tier: "STRONG BUY",
      score: 88,
      rubric: [
        { name: "Cash-on-cash", score: 10, maxPoints: 12, status: "win" },
        { name: "Cap rate", score: 10, maxPoints: 15, status: "ok" },
        { name: "DSCR", score: 15, maxPoints: 15, status: "win" },
        { name: "IRR", score: 20, maxPoints: 22, status: "win" },
        { name: "Vacancy tolerance", score: 10, maxPoints: 10, status: "win" },
        { name: "Price-to-rent", score: 6, maxPoints: 7, status: "win" },
        { name: "Total ROI", score: 10, maxPoints: 10, status: "win" },
      ],
      summary: "Excellent cash flow fundamentals with strong DSCR coverage. Low entry point and solid rent-to-price ratio. Higher maintenance reserves account for older property.",
    },
    grade: "A",
    provenance: {
      purchasePrice: { source: "zillow-listing", confidence: "high" },
      monthlyRent: { source: "rentcast", confidence: "high", tooltip: "Strong comp pool (12 rentals)" },
      annualPropertyTax: { source: "state-investor-rate", confidence: "medium", tooltip: "IN non-homestead rate" },
      annualAppreciationPercent: { source: "fhfa-hpi", confidence: "high", tooltip: "Indianapolis MSA" },
    },
    createdAt: new Date("2024-01-16T08:45:00"),
    cashFlowTrend: generateCashFlowTrend(497, 0.06),
  },
  {
    id: "lead-004",
    propertyFacts: {
      beds: 3,
      baths: 2,
      sqft: 1650,
      yearBuilt: 2008,
      propertyType: "Townhouse",
      lastSalePrice: 310000,
      lastSaleDate: "2022-01-18",
      address: "2234 Riverstone Court",
      city: "Charlotte",
      state: "NC",
      zip: "28269",
    },
    inputs: {
      purchase: {
        purchasePrice: 365000,
        downPaymentPercent: 20,
        closingCostsPercent: 3,
        rehabCosts: 5000,
      },
      financing: {
        loanInterestRate: 6.875,
        loanTermYears: 30,
      },
      income: {
        monthlyRent: 2400,
        otherMonthlyIncome: 0,
        vacancyRatePercent: 5,
      },
      operatingExpenses: {
        annualPropertyTax: 3650,
        annualInsurance: 1600,
        monthlyHOA: 185,
        monthlyUtilities: 0,
        maintenancePercent: 5,
        propertyManagementPercent: 8,
        capexReservePercent: 5,
      },
      growthAndExit: {
        annualAppreciationPercent: 4.5,
        annualRentGrowthPercent: 3,
        annualExpenseGrowthPercent: 2.5,
        sellingCostsPercent: 6,
        holdPeriodYears: 10,
      },
    },
    outputs: {
      upfront: {
        loanAmount: 292000,
        downPayment: 73000,
        closingCosts: 10950,
        totalCashInvested: 88950,
      },
      monthly: {
        monthlyMortgagePayment: 1918,
        monthlyGrossRent: 2400,
        monthlyEffectiveIncome: 2280,
        monthlyOperatingExpenses: 1105,
        monthlyCashFlow: -743,
        monthlyNOI: 1175,
      },
      annual: {
        annualGrossIncome: 28800,
        annualEffectiveIncome: 27360,
        annualOperatingExpenses: 13260,
        annualNOI: 14100,
        annualDebtService: 23016,
        annualCashFlow: -8916,
      },
      ratios: {
        capRate: 3.81,
        cashOnCashReturn: -10.02,
        dscr: 0.61,
        irr: 9.4,
        grossRentMultiplier: 12.85,
        onePercentRule: 0.65,
        operatingExpenseRatio: 0.48,
        breakEvenOccupancy: 1.33,
      },
      exit: {
        salePrice: 566000,
        sellingCosts: 33960,
        loanBalanceAtExit: 235500,
        netSaleProceeds: 296540,
        totalCashFlow: -89160,
        totalPrincipalPaydown: 56500,
        totalAppreciation: 201000,
        totalProfit: 118430,
        totalROI: 133.1,
        averageAnnualReturn: 13.31,
      },
      projections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        grossRent: Math.round(28800 * Math.pow(1.03, i)),
        effectiveGrossIncome: Math.round(27360 * Math.pow(1.03, i)),
        operatingExpenses: Math.round(13260 * Math.pow(1.025, i)),
        noi: Math.round(14100 * Math.pow(1.02, i)),
        debtService: 23016,
        cashFlow: Math.round(-8916 + i * 850),
        principalPaid: Math.round(4250 + i * 280),
        interestPaid: Math.round(18766 - i * 280),
        loanBalanceEnd: Math.round(292000 - (4250 + i * 280) * (i + 1)),
        propertyValueEnd: Math.round(370000 * Math.pow(1.045, i + 1)),
        equityEnd: Math.round(78000 + (4250 + i * 280) * (i + 1) + 370000 * (Math.pow(1.045, i + 1) - 1)),
        cumulativeCashFlow: Math.round((-8916 + i * 425) * (i + 1)),
      })),
    },
    verdict: {
      tier: "AVOID",
      score: 31,
      rubric: [
        { name: "Cash-on-cash", score: 0, maxPoints: 12, status: "fail" },
        { name: "Cap rate", score: 5, maxPoints: 15, status: "warn" },
        { name: "DSCR", score: 0, maxPoints: 15, status: "fail" },
        { name: "IRR", score: 13, maxPoints: 22, status: "ok" },
        { name: "Vacancy tolerance", score: 0, maxPoints: 10, status: "fail" },
        { name: "Price-to-rent", score: 3, maxPoints: 7, status: "warn" },
        { name: "Total ROI", score: 7, maxPoints: 10, status: "ok" },
      ],
      summary: "Severe negative cash flow. DSCR below 1.0 with break-even occupancy over 100%. HOA fees compress margins. Appreciation play only.",
    },
    grade: "F",
    provenance: {
      purchasePrice: { source: "zillow-listing", confidence: "high" },
      monthlyRent: { source: "zillow-listing", confidence: "low" },
      monthlyHOA: { source: "zillow-listing", confidence: "high" },
      annualPropertyTax: { source: "rentcast", confidence: "high" },
    },
    createdAt: new Date("2024-01-13T16:10:00"),
    cashFlowTrend: generateCashFlowTrend(-743, 0.12),
  },
  {
    id: "lead-005",
    propertyFacts: {
      beds: 4,
      baths: 3,
      sqft: 2450,
      yearBuilt: 2019,
      propertyType: "Single Family",
      lastSalePrice: 485000,
      lastSaleDate: "2022-08-05",
      address: "7891 Sunset Ridge",
      city: "Phoenix",
      state: "AZ",
      zip: "85044",
    },
    inputs: {
      purchase: {
        purchasePrice: 545000,
        downPaymentPercent: 25,
        closingCostsPercent: 3,
        rehabCosts: 0,
      },
      financing: {
        loanInterestRate: 6.875,
        loanTermYears: 30,
      },
      income: {
        monthlyRent: 3450,
        otherMonthlyIncome: 150,
        vacancyRatePercent: 5,
      },
      operatingExpenses: {
        annualPropertyTax: 4360,
        annualInsurance: 2200,
        monthlyHOA: 95,
        monthlyUtilities: 0,
        maintenancePercent: 4,
        propertyManagementPercent: 8,
        capexReservePercent: 4,
      },
      growthAndExit: {
        annualAppreciationPercent: 4.8,
        annualRentGrowthPercent: 3.5,
        annualExpenseGrowthPercent: 2.5,
        sellingCostsPercent: 6,
        holdPeriodYears: 10,
      },
    },
    outputs: {
      upfront: {
        loanAmount: 408750,
        downPayment: 136250,
        closingCosts: 16350,
        totalCashInvested: 152600,
      },
      monthly: {
        monthlyMortgagePayment: 2685,
        monthlyGrossRent: 3600,
        monthlyEffectiveIncome: 3420,
        monthlyOperatingExpenses: 1276,
        monthlyCashFlow: -541,
        monthlyNOI: 2144,
      },
      annual: {
        annualGrossIncome: 43200,
        annualEffectiveIncome: 41040,
        annualOperatingExpenses: 15312,
        annualNOI: 25728,
        annualDebtService: 32220,
        annualCashFlow: -6492,
      },
      ratios: {
        capRate: 4.72,
        cashOnCashReturn: -4.25,
        dscr: 0.80,
        irr: 12.6,
        grossRentMultiplier: 12.62,
        onePercentRule: 0.66,
        operatingExpenseRatio: 0.37,
        breakEvenOccupancy: 0.92,
      },
      exit: {
        salePrice: 853000,
        sellingCosts: 51180,
        loanBalanceAtExit: 329800,
        netSaleProceeds: 472020,
        totalCashFlow: -64920,
        totalPrincipalPaydown: 78950,
        totalAppreciation: 308000,
        totalProfit: 254500,
        totalROI: 166.8,
        averageAnnualReturn: 16.68,
      },
      projections: Array.from({ length: 10 }, (_, i) => ({
        year: i + 1,
        grossRent: Math.round(43200 * Math.pow(1.035, i)),
        effectiveGrossIncome: Math.round(41040 * Math.pow(1.035, i)),
        operatingExpenses: Math.round(15312 * Math.pow(1.025, i)),
        noi: Math.round(25728 * Math.pow(1.03, i)),
        debtService: 32220,
        cashFlow: Math.round(-6492 + i * 980),
        principalPaid: Math.round(5940 + i * 395),
        interestPaid: Math.round(26280 - i * 395),
        loanBalanceEnd: Math.round(408750 - (5940 + i * 395) * (i + 1)),
        propertyValueEnd: Math.round(545000 * Math.pow(1.048, i + 1)),
        equityEnd: Math.round(136250 + (5940 + i * 395) * (i + 1) + 545000 * (Math.pow(1.048, i + 1) - 1)),
        cumulativeCashFlow: Math.round((-6492 + i * 490) * (i + 1)),
      })),
    },
    verdict: {
      tier: "BORDERLINE",
      score: 56,
      rubric: [
        { name: "Cash-on-cash", score: 0, maxPoints: 12, status: "fail" },
        { name: "Cap rate", score: 9, maxPoints: 15, status: "ok" },
        { name: "DSCR", score: 5, maxPoints: 15, status: "warn" },
        { name: "IRR", score: 16, maxPoints: 22, status: "ok" },
        { name: "Vacancy tolerance", score: 5, maxPoints: 10, status: "warn" },
        { name: "Price-to-rent", score: 4, maxPoints: 7, status: "ok" },
        { name: "Total ROI", score: 9, maxPoints: 10, status: "win" },
      ],
      summary: "Negative near-term cash flow offset by strong appreciation market. Phoenix rent growth could flip to positive within 3-4 years. Consider rate buydown.",
    },
    grade: "C",
    provenance: {
      purchasePrice: { source: "zillow-listing", confidence: "high" },
      monthlyRent: { source: "rent-comps", confidence: "high", tooltip: "8 nearby comps" },
      annualPropertyTax: { source: "rentcast", confidence: "high" },
      annualAppreciationPercent: { source: "fhfa-hpi", confidence: "high", tooltip: "Phoenix MSA 10yr CAGR" },
    },
    createdAt: new Date("2024-01-16T11:20:00"),
    cashFlowTrend: generateCashFlowTrend(-541, 0.1),
  },
]

export function getLeadById(id: string): Lead | undefined {
  return mockLeads.find((lead) => lead.id === id)
}
